language: c

os:
  - linux

dist:
  - bionic

compiler:
  - gcc

env:
  - QEMU_VERSION=4.2.0
addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main universe"
    #packages:
    #  - qemu-user=2.7.0

before_install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y clang-format-6.0


script:
  - bash -e travis-qemu.sh
  - make VERBOSE=1
  - make check
  - sh .ci/check-format.sh

after_script:
  - $HOME/qemu/bin/qemu-img --version
