language: c

os:
  - linux

dist:
  - focal

compiler:
  - gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/redis-server'
    packages:
    - redis-tools
    - redis-server
    - qemu-user

before_install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y clang-format-6.0

script:
  - make VERBOSE=1      
  - make check
  - sh .ci/check-format.sh
