language: c

os:
  - linux

dist:
  - bionic

compiler:
  - gcc

addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main universe"
    #packages:
    #  - qemu-user

before_install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y clang-format-6.0
  - sudo apt install qemu-user



script:
  - make VERBOSE=1
  - make check
  - sh .ci/check-format.sh
